package bdstudia;

import bdstudia.Bank;
import javax.persistence.EntityManager;
import javax.persistence.NoResultException;
import javax.swing.JOptionPane;
import org.hibernate.Session;
import org.hibernate.SessionFactory;


/**
 *
 * @author krystofair
 */

public class BankJFrame extends javax.swing.JFrame {
    //referencja do obiektu globalnego factory;
    SessionFactory sf_ref;
    private Bank bank;

    /**
     * Creates new form BankJFrame
     * @param sf - reference to factory
     */
    public BankJFrame(SessionFactory sf) {
        this.sf_ref = sf;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EXECUTE_BUTTON = new javax.swing.JButton();
        jTF_bank_name = new javax.swing.JTextField();
        jTF_bank_adres = new javax.swing.JTextField();
        jTF_bank_miasto = new javax.swing.JTextField();
        jTF_bank_kodpoczt = new javax.swing.JTextField();
        jTF_bank_kraj = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DODAWANIE BANKU");

        EXECUTE_BUTTON.setText("Dodaj");
        EXECUTE_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXECUTE_BUTTONActionPerformed(evt);
            }
        });

        jTF_bank_name.setToolTipText("Nazwa Banku");
        jTF_bank_name.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jTF_bank_adres.setToolTipText("Adres");

        jTF_bank_miasto.setToolTipText("Miasto");

        jTF_bank_kodpoczt.setToolTipText("Kod Pocztowy");

        jTF_bank_kraj.setToolTipText("Kraj");

        jLabel2.setText("Nazwa Banku");

        jLabel3.setText("Adres");

        jLabel4.setText("Miasto");

        jLabel5.setText("Kod Pocztowy");

        jLabel6.setText("Kraj");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTF_bank_kraj))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTF_bank_adres))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTF_bank_name))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTF_bank_kodpoczt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTF_bank_miasto))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(EXECUTE_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTF_bank_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTF_bank_adres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTF_bank_miasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTF_bank_kodpoczt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTF_bank_kraj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EXECUTE_BUTTON)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EXECUTE_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXECUTE_BUTTONActionPerformed
        // zebranie nowych informacji.
        bank = new Bank();
        bank.setAdres(jTF_bank_adres.getText());
        bank.setKodpocztowy(jTF_bank_kodpoczt.getText());
        bank.setKraj(jTF_bank_kraj.getText());
        bank.setMiasto(jTF_bank_miasto.getText());
        bank.setNazwa(jTF_bank_name.getText());
        if(!bank.validate() ) {
            JOptionPane.showMessageDialog(this, "Nie poprawne dane, wype³nij wszystkie komórki",
                    "Dodawanie banku. B³¹d.", JOptionPane.WARNING_MESSAGE);
        } else {
            Session sesja = sf_ref.openSession();
            EntityManager em = sf_ref.createEntityManager();
            try {
                Bank bank_wynik = em.createQuery("from banki where miasto = :miasto " +
                        "AND adres = :adres", Bank.class)
                        .setParameter("miasto", bank.getMiasto())
                        .setParameter("adres", bank.getAdres())
                        .getSingleResult();
                JOptionPane.showMessageDialog(this, "Bank w tym mieœcie o podanym adresie ju¿ istnieje, popraw dane lub zamknij okno formularza",
                        "Dodawanie banku. B³¹d.", JOptionPane.WARNING_MESSAGE);

            } catch(NoResultException nre) {
                //dodawania banku.
                sesja.beginTransaction();
                sesja.save(bank);
                sesja.getTransaction().commit();
                sesja.close();
                JOptionPane.showMessageDialog(this, "Pomyœlnie dodano bank do bazy.",
                        "Dodawanie banku. Info.", JOptionPane.INFORMATION_MESSAGE);
            } catch(java.lang.IllegalStateException ise) {
                // entity manager was close, now here isn't a problem
                // Problem was here, because running from normal Main program - no in loop of AWT.
                JOptionPane.showMessageDialog(this, "DEBUG IllegalStateException in BankFormularz.");
            } finally {
                em.close();
            }
        }
    }//GEN-LAST:event_EXECUTE_BUTTONActionPerformed

    void pokaz_formularz(){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BankJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BankJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BankJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        BankJFrame t = this;
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                t.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EXECUTE_BUTTON;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTF_bank_adres;
    private javax.swing.JTextField jTF_bank_kodpoczt;
    private javax.swing.JTextField jTF_bank_kraj;
    private javax.swing.JTextField jTF_bank_miasto;
    private javax.swing.JTextField jTF_bank_name;
    // End of variables declaration//GEN-END:variables
}
