package bdstudia;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.persistence.criteria.CriteriaBuilder;
import javax.swing.JOptionPane;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.Query;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;

/**
 *
 * @author krystofair
 */
public class PobranieForm extends javax.swing.JFrame {
    
   SessionFactory factory;
   Osoba LastPerson;
   Pobranie pobranie;
   Date PolDataPobrania;
   
   public void wczytajOsobe(Osoba o) {
       this.LastPerson = o;
   }

    /**
     * Creates new form PobranieForm
     */
   
    public PobranieForm(SessionFactory factory_ref) {
        this.factory = factory_ref;
        this.PolDataPobrania = new Date();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLabel1 = new javax.swing.JLabel();
        PobierzKrewBtn = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaZnalezionychOsob = new javax.swing.JList<>();
        ImieEditText2 = new javax.swing.JTextField();
        NazwiskoEditText = new javax.swing.JTextField();
        PeselEditText = new javax.swing.JTextField();
        AdresEditText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        SzukajOsobyBtn = new javax.swing.JButton();
        FromLastFormBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListaZnalezionychBankow = new javax.swing.JList<>();
        NazwaBankuEditText3 = new javax.swing.JTextField();
        AdresBankuEditText1 = new javax.swing.JTextField();
        MiastoBankuEditText1 = new javax.swing.JTextField();
        KrajBankuEditText1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        SzukajBankuBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        ProduktComboBox = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        DateChoiceBtn = new javax.swing.JButton();
        CzasGodzinyComboBox = new javax.swing.JComboBox<>();
        CzasMinutyComboBox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("POBIERANIE KRWI.");
        setResizable(false);

        PobierzKrewBtn.setText("Pobierz Krew");
        PobierzKrewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PobierzKrewBtnActionPerformed(evt);
            }
        });

        ListaZnalezionychOsob.setModel(new OsobyZnalezioneModel());
        ListaZnalezionychOsob.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(ListaZnalezionychOsob);

        ImieEditText2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ImieEditText2.setName(""); // NOI18N
        ImieEditText2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ImieEditText2KeyTyped(evt);
            }
        });

        NazwiskoEditText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NazwiskoEditText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NazwiskoEditTextKeyTyped(evt);
            }
        });

        PeselEditText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PeselEditText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PeselEditTextKeyTyped(evt);
            }
        });

        AdresEditText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AdresEditText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AdresEditTextKeyTyped(evt);
            }
        });

        jLabel2.setText("Imie :");

        jLabel3.setText("Nazwisko :");

        jLabel4.setText("PESEL :");

        jLabel5.setText("Adres :");

        SzukajOsobyBtn.setText("Szukaj");
        SzukajOsobyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SzukajHandler(evt);
            }
        });

        FromLastFormBtn.setText("Z ostatniego formularza");
        FromLastFormBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FromLastFormBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NazwiskoEditText, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                            .addComponent(PeselEditText, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AdresEditText, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ImieEditText2, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(SzukajOsobyBtn)
                        .addGap(31, 31, 31)
                        .addComponent(FromLastFormBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ImieEditText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(NazwiskoEditText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(PeselEditText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(AdresEditText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SzukajOsobyBtn)
                    .addComponent(FromLastFormBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Wybór Osoby", jPanel1);

        ListaZnalezionychBankow.setModel(new BankiZnalezioneListModel());
        ListaZnalezionychBankow.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(ListaZnalezionychBankow);

        NazwaBankuEditText3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NazwaBankuEditText3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NazwaBankuEditText3KeyTyped(evt);
            }
        });

        AdresBankuEditText1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AdresBankuEditText1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AdresBankuEditText1KeyTyped(evt);
            }
        });

        MiastoBankuEditText1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MiastoBankuEditText1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MiastoBankuEditText1KeyTyped(evt);
            }
        });

        KrajBankuEditText1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        KrajBankuEditText1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                KrajBankuEditText1KeyTyped(evt);
            }
        });

        jLabel6.setText("Nazwa:");

        jLabel7.setText("Adres:");

        jLabel8.setText("Miasto:");

        jLabel9.setText("Kraj:");

        SzukajBankuBtn.setText("Szukaj");
        SzukajBankuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SzukajHandler(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MiastoBankuEditText1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AdresBankuEditText1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NazwaBankuEditText3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(KrajBankuEditText1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(SzukajBankuBtn, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(NazwaBankuEditText3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(AdresBankuEditText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(MiastoBankuEditText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(KrajBankuEditText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(SzukajBankuBtn)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Wybór Banku", jPanel3);

        jLabel10.setText("Data Pobrania:");

        ProduktComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "osocze", "krew pe³na", "p³ytki krwi" }));

        jLabel12.setText("Wytwarzany produkt:");

        DateChoiceBtn.setText(pullOnlyDate(null));
        DateChoiceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateChoiceBtnActionPerformed(evt);
            }
        });

        CzasGodzinyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        CzasGodzinyComboBox.setSelectedItem(pullOnlyTime(null, true)
        );

        CzasMinutyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        CzasMinutyComboBox.setSelectedItem(pullOnlyTime(null, false));

        jLabel11.setText(":");

        jLabel14.setText("Godzina:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DateChoiceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CzasGodzinyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CzasMinutyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(82, 82, 82)
                                .addComponent(ProduktComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PobierzKrewBtn)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(DateChoiceBtn)
                    .addComponent(CzasGodzinyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CzasMinutyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProduktComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(PobierzKrewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void ImieEditText2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ImieEditText2KeyTyped
        if(ImieEditText2.getText().length() > 255
        || !Character.isAlphabetic(evt.getKeyChar()) 
        && evt.getKeyChar() != ' ') {
            evt.consume();
        }
    }//GEN-LAST:event_ImieEditText2KeyTyped

    private void NazwiskoEditTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NazwiskoEditTextKeyTyped
        if(!Character.isAlphabetic(evt.getKeyChar()) && evt.getKeyChar() != ' ' &&
                evt.getKeyChar() != '-') {
            evt.consume();
        }
    }//GEN-LAST:event_NazwiskoEditTextKeyTyped

    private void PeselEditTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PeselEditTextKeyTyped
        if(!((evt.getKeyChar()>='0') && (evt.getKeyChar()<='9'))
        || PeselEditText.getText().length() > 11)
            evt.consume();
    }//GEN-LAST:event_PeselEditTextKeyTyped

    private void AdresEditTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AdresEditTextKeyTyped
        if(AdresEditText.getText().length() > 255 ||
                !Character.isLetterOrDigit(evt.getKeyChar()) &&
                evt.getKeyChar()!= ' ' && evt.getKeyChar() != '/') {
            evt.consume();
        }
    }//GEN-LAST:event_AdresEditTextKeyTyped

    private void NazwaBankuEditText3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NazwaBankuEditText3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_NazwaBankuEditText3KeyTyped

    private void AdresBankuEditText1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AdresBankuEditText1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_AdresBankuEditText1KeyTyped

    private void MiastoBankuEditText1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MiastoBankuEditText1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_MiastoBankuEditText1KeyTyped

    private void KrajBankuEditText1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KrajBankuEditText1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_KrajBankuEditText1KeyTyped

    private void SzukajHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SzukajHandler
        Session sesja = factory.openSession();
        CriteriaBuilder cb = sesja.getCriteriaBuilder();
        List<Predicate> predicates = new ArrayList<>();
        if(evt.getSource() == SzukajOsobyBtn) {
            CriteriaQuery<Osoba> cr = cb.createQuery(Osoba.class);
            Root<Osoba> root = cr.from(Osoba.class);
            if(!PeselEditText.getText().isBlank()) {
                String pesel = PeselEditText.getText();
                // dodanie predicates - czyli takiego obiektowego warunku XD
                predicates.add(cb.like(root.get("pesel"), pesel + "%"));
//                if(Validator.isOnlyDigit(pesel))
//                else
//                    JOptionPane.showMessageDialog(
//                        this, "Wpisany nr. PESEL jest niepoprawny.",
//                        "B³¹d w nr. PESEL.", JOptionPane.WARNING_MESSAGE);
            } else {
                if(!ImieEditText2.getText().isBlank()) {
                    String imie = ImieEditText2.getText();
                    predicates.add(cb.like(root.get("imie"), imie+"%"));
                }
                if (!NazwiskoEditText.getText().isBlank()) {
                    String nazwisko = NazwiskoEditText.getText();
                    predicates.add(cb.like(root.get("nazwisko"), nazwisko+"%"));
                }
                if (!AdresEditText.getText().isBlank()) {
                    String adres = AdresEditText.getText();
                    predicates.add(cb.like(root.get("adres"), "%"+adres+"%"));
//                   if(Validator.validateSQL(adres))
//                    else
//                        JOptionPane.showMessageDialog(this, "Wpisano b³êdne znaki");
//                    restr.add(Restrictions.ilike("adres", AdresEditText.getText(), MatchMode.START));
                }
            }
            Predicate[] preds = new Predicate[predicates.size()];
            for(int i=0; i<predicates.size(); ++i) preds[i] = predicates.get(i);
            if(predicates.size() > 0) {
                cr.where(preds);
                Query query = sesja.createQuery(cr);
                ((OsobyZnalezioneModel)
                    ListaZnalezionychOsob.getModel())
                    .dodajOsoby(query.getResultList());
            } else {
                JOptionPane.showMessageDialog(this, "Musisz wype³niæ przynajmniej jedno pole.");
            }
        }
        if(evt.getSource() == SzukajBankuBtn) {
            CriteriaQuery<Bank> cr = cb.createQuery(Bank.class);
            Root<Bank> root = cr.from(Bank.class);
            if(!NazwaBankuEditText3.getText().isBlank()) {
                String nazwa = NazwaBankuEditText3.getText();
                predicates.add(cb.like(root.get("nazwa"), nazwa + "%"));
            }
            if(!AdresBankuEditText1.getText().isBlank()) {
                String adres = AdresBankuEditText1.getText();
                predicates.add(cb.like(root.get("adres"), "%"+adres+"%"));
            }
            if (!MiastoBankuEditText1.getText().isBlank()) {
                String miasto = MiastoBankuEditText1.getText();
                predicates.add(cb.like(root.get("miasto"), miasto+"%"));
            }
            if (!KrajBankuEditText1.getText().isBlank()) {
                String kraj = KrajBankuEditText1.getText();
                predicates.add(cb.like(root.get("kraj"), kraj+"%"));
            }
            Predicate[] preds = new Predicate[predicates.size()];
            for(int i=0; i<predicates.size(); ++i) preds[i] = predicates.get(i);
            if(predicates.size() > 0) {
                cr.where(preds);
                Query query = sesja.createQuery(cr);
                ((BankiZnalezioneListModel)
                    ListaZnalezionychBankow.getModel())
                    .dodajBanki(query.getResultList());
            } else {
                JOptionPane.showMessageDialog(this, "Musisz wype³niæ przynajmniej jedno pole.");
            }
        }
        sesja.close(); // zamykanie sesji
    }//GEN-LAST:event_SzukajHandler

    private void FromLastFormBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FromLastFormBtnActionPerformed
        if(LastPerson != null) {
            PeselEditText.setText(LastPerson.getPesel());
            //SzukajHandler(new java.awt.event.ActionEvent(SzukajOsobyBtn, 0, "action performed"));
            ((OsobyZnalezioneModel)ListaZnalezionychOsob.getModel()).dodajOsoby(Arrays.asList(LastPerson));
            ListaZnalezionychOsob.setSelectedIndex(0);
            AdresEditText.setText(LastPerson.getAdres());
            ImieEditText2.setText(LastPerson.getImie());
            NazwiskoEditText.setText(LastPerson.getNazwisko());
        }
    }//GEN-LAST:event_FromLastFormBtnActionPerformed

    private void DateChoiceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateChoiceBtnActionPerformed
        DatePicker dp = new DatePicker(this);
        Date data = dp.setPickedDate();
        if(data != null) {
            if(data.getTime() <= System.currentTimeMillis()) {
                DateChoiceBtn.setText(pullOnlyDate(data));
            } else {
                DateChoiceBtn.setText(pullOnlyDate(new Date(System.currentTimeMillis())));
            }
            this.PolDataPobrania.setTime(data.getTime());
        }
    }//GEN-LAST:event_DateChoiceBtnActionPerformed

    private void PobierzKrewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PobierzKrewBtnActionPerformed
        // no to walidacja czy wszystko pobrane itd.
        int id_banku, id_osoby;
         try {
            id_osoby = ((OsobyZnalezioneModel) ListaZnalezionychOsob.getModel()).getIdOsoby(ListaZnalezionychOsob.getSelectedIndex());
        } catch(NullPointerException npe) {
            JOptionPane.showMessageDialog(this, "Nie wybrano osoby.");
            return;
        }
        try {
            id_banku = ((BankiZnalezioneListModel) ListaZnalezionychBankow.getModel()).getIdBanku(ListaZnalezionychBankow.getSelectedIndex());
        } catch(NullPointerException npe) {
            JOptionPane.showMessageDialog(this, "Nie wybrano banku.");
            return;
        }
        this.pobranie = new Pobranie();
        this.pobranie.setDatapobrania(composeDateTogether());
        this.pobranie.setIdbanku(id_banku);
        this.pobranie.setIdosoby(id_osoby);
        this.pobranie.setIdproduktu(ProduktComboBox.getSelectedIndex()+1);
        JOptionPane.showMessageDialog(this,this.pobranie.toString());
    }//GEN-LAST:event_PobierzKrewBtnActionPerformed

    private Date composeDateTogether() {
        Calendar c = Calendar.getInstance();
        c.setTime(this.PolDataPobrania);
        long czas_w_ms = c.get(Calendar.MINUTE)*60+c.get(Calendar.HOUR_OF_DAY)*3600+c.get(Calendar.SECOND);
        czas_w_ms *= 1000;
        c.setTimeInMillis(this.PolDataPobrania.getTime() - czas_w_ms);
        c.add(Calendar.HOUR_OF_DAY, Integer.parseInt((String) CzasGodzinyComboBox.getSelectedItem()));
        c.add(Calendar.MINUTE, Integer.parseInt((String) CzasMinutyComboBox.getSelectedItem()));
        return c.getTime();
    }
    
    private String pullOnlyTime(Date d, boolean hours){
        if(d == null)
            d = new Date(System.currentTimeMillis());
        return (hours) ? new java.text.SimpleDateFormat("HH").format(d)
                : new java.text.SimpleDateFormat("mm").format(d);
    }
    
    private String pullOnlyDate(Date d) {
        if(d == null)
            d = new Date(System.currentTimeMillis());
        return new java.text.SimpleDateFormat("EEEE, dd / MM / yyyyy").format(d);
    }
    
    public void pokazFormularz() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PobranieForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PobranieForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PobranieForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PobranieForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        PobranieForm t = this;
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               t.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdresBankuEditText1;
    private javax.swing.JTextField AdresEditText;
    private javax.swing.JComboBox<String> CzasGodzinyComboBox;
    private javax.swing.JComboBox<String> CzasMinutyComboBox;
    private javax.swing.JButton DateChoiceBtn;
    private javax.swing.JButton FromLastFormBtn;
    private javax.swing.JTextField ImieEditText2;
    private javax.swing.JTextField KrajBankuEditText1;
    private javax.swing.JList<String> ListaZnalezionychBankow;
    private javax.swing.JList<String> ListaZnalezionychOsob;
    private javax.swing.JTextField MiastoBankuEditText1;
    private javax.swing.JTextField NazwaBankuEditText3;
    private javax.swing.JTextField NazwiskoEditText;
    private javax.swing.JTextField PeselEditText;
    private javax.swing.JButton PobierzKrewBtn;
    private javax.swing.JComboBox<String> ProduktComboBox;
    private javax.swing.JButton SzukajBankuBtn;
    private javax.swing.JButton SzukajOsobyBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
