package bdstudia;

import java.awt.event.KeyEvent;
import java.util.List;
import javax.persistence.NoResultException;
import javax.persistence.criteria.CriteriaBuilder;
import javax.swing.JOptionPane;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.criterion.MatchMode;
import org.hibernate.criterion.Restrictions;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Expression;

/**
 *
 * @author krystofair
 */
public class PobranieForm extends javax.swing.JFrame {
    
   SessionFactory factory;

    /**
     * Creates new form PobranieForm
     */
   
    public PobranieForm(SessionFactory factory_ref) {
        this.factory = factory_ref;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jButton1 = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaZnalezionychOsob = new javax.swing.JList<>();
        ImieEditText2 = new javax.swing.JTextField();
        NazwiskoEditText = new javax.swing.JTextField();
        PeselEditText = new javax.swing.JTextField();
        AdresEditText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        SzukajOsobyBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListaZnalezionychBankow = new javax.swing.JList<>();
        NazwaBankuEditText3 = new javax.swing.JTextField();
        AdresBankuEditText1 = new javax.swing.JTextField();
        MiastoBankuEditText1 = new javax.swing.JTextField();
        KrajBankuEditText1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        SzukajBankuBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("POBIERANIE KRWI.");

        jButton1.setText("Dalej");

        ListaZnalezionychOsob.setModel(new OsobyZnalezioneModel());
        ListaZnalezionychOsob.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(ListaZnalezionychOsob);

        ImieEditText2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ImieEditText2.setName(""); // NOI18N
        ImieEditText2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ImieEditText2KeyTyped(evt);
            }
        });

        NazwiskoEditText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NazwiskoEditText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NazwiskoEditTextKeyTyped(evt);
            }
        });

        PeselEditText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PeselEditText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PeselEditTextKeyTyped(evt);
            }
        });

        AdresEditText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AdresEditText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AdresEditTextKeyTyped(evt);
            }
        });

        jLabel2.setText("Imie :");

        jLabel3.setText("Nazwisko :");

        jLabel4.setText("PESEL :");

        jLabel5.setText("Adres :");

        SzukajOsobyBtn.setText("Szukaj");
        SzukajOsobyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SzukajHandler(evt);
            }
        });

        jButton2.setText("Ostatnia Dodana Osoba");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(NazwiskoEditText, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                                    .addComponent(PeselEditText, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(AdresEditText, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ImieEditText2)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(SzukajOsobyBtn)
                                .addGap(31, 31, 31)
                                .addComponent(jButton2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ImieEditText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(NazwiskoEditText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(PeselEditText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(AdresEditText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SzukajOsobyBtn)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Wybór Osoby", jPanel1);

        ListaZnalezionychBankow.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(ListaZnalezionychBankow);

        NazwaBankuEditText3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NazwaBankuEditText3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NazwaBankuEditText3KeyTyped(evt);
            }
        });

        AdresBankuEditText1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AdresBankuEditText1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AdresBankuEditText1KeyTyped(evt);
            }
        });

        MiastoBankuEditText1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MiastoBankuEditText1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MiastoBankuEditText1KeyTyped(evt);
            }
        });

        KrajBankuEditText1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        KrajBankuEditText1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                KrajBankuEditText1KeyTyped(evt);
            }
        });

        jLabel6.setText("Nazwa:");

        jLabel7.setText("Adres:");

        jLabel8.setText("Miasto:");

        jLabel9.setText("Kraj:");

        SzukajBankuBtn.setText("Szukaj");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AdresBankuEditText1)
                            .addComponent(NazwaBankuEditText3)
                            .addComponent(MiastoBankuEditText1)
                            .addComponent(KrajBankuEditText1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(SzukajBankuBtn)
                        .addGap(0, 393, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(NazwaBankuEditText3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(AdresBankuEditText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(MiastoBankuEditText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(KrajBankuEditText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(SzukajBankuBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Wybór Banku", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void ImieEditText2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ImieEditText2KeyTyped
        char c = evt.getKeyChar();
        if(!(((c>=65)&&(c<=90)) || ((c>=97)&&(c<=122))))
        {
            evt.consume();
        }else if((((c>=65)&&(c<=90)) || ((c>=97)&&(c<=122)))){
            if(!ImieEditText2.getText().isEmpty()){
                String buff = ImieEditText2.getText() + c;
                if(buff.length()>255){
                    evt.consume();
                }
            }
        }
    }//GEN-LAST:event_ImieEditText2KeyTyped

    private void NazwiskoEditTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NazwiskoEditTextKeyTyped
        char c = evt.getKeyChar();
        if(!(((c>=65)&&(c<=90)) || ((c>=97)&&(c<=122))))
        {
            evt.consume();
        }else if((((c>=65)&&(c<=90)) || ((c>=97)&&(c<=122)))){
            if(!NazwiskoEditText.getText().isEmpty()){
                String buff = NazwiskoEditText.getText() + c;
                if(buff.length()>255){
                    evt.consume();
                }
            }
        }
    }//GEN-LAST:event_NazwiskoEditTextKeyTyped

    private void PeselEditTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PeselEditTextKeyTyped
        char c = evt.getKeyChar();
        if(!((c>='0') && (c<='9')))
        {
            evt.consume();
        }else if((c>='0') && (c<='9')){
            if(!PeselEditText.getText().isEmpty()){
                String buff = PeselEditText.getText() + c;
                if(buff.length()>11){
                    evt.consume();
                }
            }
        }

    }//GEN-LAST:event_PeselEditTextKeyTyped

    private void AdresEditTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AdresEditTextKeyTyped
        char c = evt.getKeyChar();
        if(! (((c>=65)&&(c<=90))
            || ((c>=97)&&(c<=122))
            || ((c>=47) && (c<=57))
            || (c == KeyEvent.VK_SPACE)
        ))
        {
            evt.consume();
        }else if((((c>=65)&&(c<=90))
            || ((c>=97)&&(c<=122))
            || ((c>=47) && (c<=57))
            || (c == KeyEvent.VK_SPACE)
        ))
        {
            if(!AdresEditText.getText().isEmpty()){
                String buff = AdresEditText.getText() + c;
                if(buff.length()>255){
                    evt.consume();
                }
            }
        }
    }//GEN-LAST:event_AdresEditTextKeyTyped

    private void NazwaBankuEditText3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NazwaBankuEditText3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_NazwaBankuEditText3KeyTyped

    private void AdresBankuEditText1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AdresBankuEditText1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_AdresBankuEditText1KeyTyped

    private void MiastoBankuEditText1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MiastoBankuEditText1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_MiastoBankuEditText1KeyTyped

    private void KrajBankuEditText1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KrajBankuEditText1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_KrajBankuEditText1KeyTyped

    private void SzukajHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SzukajHandler
        ((OsobyZnalezioneModel) ListaZnalezionychOsob.getModel()).clear();
        Session sesja = factory.openSession();
        CriteriaBuilder builder = factory.createEntityManager().getCriteriaBuilder();
        if(evt.getSource() == SzukajOsobyBtn) {
            if(!PeselEditText.getText().isBlank()) {
                String pesel = PeselEditText.getText();
//                if(Validator.isOnlyDigit(pesel))
//                else
//                    JOptionPane.showMessageDialog(
//                        this, "Wpisany nr. PESEL jest niepoprawny.",
//                        "B³¹d w nr. PESEL.", JOptionPane.WARNING_MESSAGE);
                builder.
                criteria.add(Restrictions.ilike("pesel", pesel, MatchMode.START));
                
                
            } else if(PeselEditText.getText().length() != 11 || PeselEditText.getText().isBlank()){
                if(!ImieEditText2.getText().isBlank()) {
                    String imie = ImieEditText2.getText();
//                    restr.add(Restrictions.ilike("imie", imie, MatchMode.START));
                }
                if (!NazwiskoEditText.getText().isBlank()) {
                    String nazwisko = NazwiskoEditText.getText();
//                    restr.add(Restrictions.ilike("nazwisko", nazwisko, MatchMode.START));
                    
                }
                if (!AdresEditText.getText().isBlank()) {
                    String adres = AdresEditText.getText(); 
//                   if(Validator.validateSQL(adres))
//                    else
//                        JOptionPane.showMessageDialog(this, "Wpisano b³êdne znaki");
//                    restr.add(Restrictions.ilike("adres", AdresEditText.getText(), MatchMode.START));
                }
            }
            // kod aktualizuj¹cy restrykcje.
            ((OsobyZnalezioneModel)
                    ListaZnalezionychOsob.getModel()).dodajOsoby(query.getResultList());
//            Criterion c = ne
//            Query opiq = sesja.createQuery(cq)
        }

        if(false) {
//                try {
//                    Query opiq = sesja.createQuery("FROM osoby", Osoba.class)
//                        .setParameter("imie", imie);
//                    ((OsobyZnalezioneModel) ListaZnalezionychOsob.getModel()).dodajOsoby(lista_wynikow);
//                } catch(NoResultException nre) {
//                    // beka z tego kodu jak ...
//                    Osoba o = new Osoba();
//                    o.setImie("Brak"); o.setNazwisko("wyników");
//                    ((OsobyZnalezioneModel)ListaZnalezionychOsob.getModel()).dodajOsoby(Arrays.asList(o));
//                }
            try {
                String nazwisko = NazwiskoEditText.getText();
                List<Osoba> lista_wynikow = sesja.createQuery("FROM osoby WHERE Nazwisko = :nazwisko", Osoba.class)
                    .setParameter("nazwisko", nazwisko).getResultList();
                ((OsobyZnalezioneModel) ListaZnalezionychOsob.getModel()).dodajOsoby(lista_wynikow);
            } catch(NoResultException nre) {
                  JOptionPane.showMessageDialog(this, "brak wyników.");
            }
        }
        if(evt.getSource() == SzukajBankuBtn) {
            
        }
        sesja.close(); // zamykanie sesji
    }//GEN-LAST:event_SzukajHandler

    /**
     * @param args the command line arguments
     */
    public void pokaz_formularz() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PobranieForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PobranieForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PobranieForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PobranieForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        var t = this;
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               t.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdresBankuEditText1;
    private javax.swing.JTextField AdresEditText;
    private javax.swing.JTextField ImieEditText2;
    private javax.swing.JTextField KrajBankuEditText1;
    private javax.swing.JList<String> ListaZnalezionychBankow;
    private javax.swing.JList<String> ListaZnalezionychOsob;
    private javax.swing.JTextField MiastoBankuEditText1;
    private javax.swing.JTextField NazwaBankuEditText3;
    private javax.swing.JTextField NazwiskoEditText;
    private javax.swing.JTextField PeselEditText;
    private javax.swing.JButton SzukajBankuBtn;
    private javax.swing.JButton SzukajOsobyBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
